### ISSUE TITLE
Colors for different types of donors and recipients are too similar

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/kidneyExchange#9]
I find it hard to distinguish between the different types of possible donors and recipients. I think this is because the colors are so similar. I think we should use colors from the d3 category colors scale to distinguish between the categories:
https://github.com/mbostock/d3/wiki/Ordinal-Scales#categorical-colors

**Comment by EmilienDupont** [comment]
I use d3 category colors now.

**Comment by cmaes** [comment]
I still find these colors too similar. They are two shades of blue and two shades of orange. I think it would be best if these colors were quite distinct. Could we use the following four colors for d3.scale.category10?

![image](https://cloud.githubusercontent.com/assets/883291/9385802/620c0b28-4726-11e5-9436-1178f10ab566.png)

**Comment by EmilienDupont** [comment]
I use category10 colors now.
